### ISSUE TITLE
Dont work anymore

### ISSUE THREAD

**Issue by pcksteal** [balena-io-playground/sdr-spectrum-monitor#3]
I've tried to install this project via balena.io cloud. But i always get an error when it's try to start at the device (Raspberry Pi 3B)

24.11.20 14:57:21 (+0100)  main  install.sh: Changing wss:// to ws://
24.11.20 14:57:21 (+0100)  main  sed: can't read openwebrx.py: No such file or directory
24.11.20 14:57:21 (+0100)  main  /usr/src/app/entry.sh: line 14: cd: htdocs: No such file or directory
24.11.20 14:57:21 (+0100)  main  sed: can't read openwebrx.js: No such file or directory
24.11.20 14:57:21 (+0100)  main  python: can't open file 'openwebrx.py': [Errno 2] No such file or directory
24.11.20 14:58:24 (+0100)  main  install.sh: Changing wss:// to ws://
24.11.20 14:58:24 (+0100)  main  sed: can't read openwebrx.py: No such file or directory
24.11.20 14:58:24 (+0100)  main  /usr/src/app/entry.sh: line 14: cd: htdocs: No such file or directory
24.11.20 14:58:24 (+0100)  main  sed: can't read openwebrx.js: No such file or directory
24.11.20 14:58:24 (+0100)  main  python: can't open file 'openwebrx.py': [Errno 2] No such file or directory
24.11.20 14:58:26 (+0100) Service exited 'main sha256:e972fe93c5909d40996a459fe6034a4de4eec91ceefa450fc6a47d3bda77c23a'

**Comment by alanb128** [comment]
I know this issue is very old, but I just ran a fresh install of the project and it seems to be running fine. I could not reproduce the error above. Please feel free to reopen if this problem persists.
